# Image
FROM node:14

# Workdir
WORKDIR /usr/src/app

# Copy the app
COPY . .

# NPM install global dependencies
RUN npm install -g serve

# Add user and switch to it
RUN useradd -m appuser
RUN chown -R appuser:appuser /usr/src/app
USER appuser

# Run npm install
RUN npm install

# Build the app
RUN npm run build

# CMD
CMD ["serve", "-s", "-l", "5000", "build"]


