# Golang image
FROM golang:1.16.10-buster

# Working directory
WORKDIR /usr/src/app

# Copy the application
COPY . .

# Add appuser and change to it
RUN useradd -m appuser
RUN chown -R appuser .
USER appuser

# Build the binary
RUN go build

# Run tests
RUN go test ./...

# CMD
CMD ["./server"]
